

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - my-network

  springboot-app:
    image: drone-management-system:latest
    container_name: drone-management-system
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      VERTX_TEMP_DIR: ${VERTX_TEMP_DIR}
      VERTX_KEYSTORE_PATH: ${VERTX_KEYSTORE_PATH}
      VERTX_KEYSTORE_PASSWORD: ${VERTX_KEYSTORE_PASSWORD}
      VERTX_TRUSTSTORE_PATH: ${VERTX_TRUSTSTORE_PATH}
      VERTX_TRUSTSTORE_PASSWORD: ${VERTX_TRUSTSTORE_PASSWORD}

networks:
  my-network:
    driver: bridge
