version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drone-management-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"

  drone-management-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: drone-management-system:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: