{{- range .Values.env }}
  {{- $valueTrimmed := .value | trim }}
  {{- $isFile := hasPrefix "files/" $valueTrimmed }}

  {{- if $isFile }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  {{ .name }}: |- {{ $.Files.Get .value | indent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-config
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  {{- range .Values.env }}
    {{- $valueTrimmed := .value | trim }}
    {{- $isFile := hasPrefix "files/" $valueTrimmed  }}
    {{- if not $isFile }}
      {{ .name }}: {{ tpl .value $ | quote }}
    {{- end }}
  {{- end }}
