{{- range .Values.configMaps }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  {{- if eq .datatype "json" }}
  {{ .name }}: |-
    {{ .data | toJson }}
  {{- end }}
  {{- if eq .datatype "properties" }}
  {{ .name }}: |-
{{ .data | nindent 4 }}
  {{- end }}
  {{- if eq .datatype "xml" }}
  {{ .name }}: |-
    {{ .data | nindent 4 }}
  {{- end }}
{{- end }}











