apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kuma-app
  labels:
    app: postgres
data:
  POSTGRES_DB: test_db
  POSTGRES_USER: hello
  POSTGRES_PASSWORD: topsecret
---
apiVersion: v1
kind: Service
metadata:
  namespace: kuma-app
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kuma-app
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: kuma-app
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
---